services:
  - type: web
    name: travel-planner-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: travel_secret_key
      - key: DATABASE_URL
        value: sqlite:///planner.db
